// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9wiT68SQXRwXXVJCvy1_eckNE48ZFEPM',
    appId: '1:866872221545:web:d12ecd25363b9a629ae7f8',
    messagingSenderId: '866872221545',
    projectId: 'doctor-appointment-app-bb40a',
    authDomain: 'doctor-appointment-app-bb40a.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-bb40a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBaiKgWmYOeX9uMuqyidnzr9MtWwLxMac',
    appId: '1:866872221545:android:ab59a37b054f07b69ae7f8',
    messagingSenderId: '866872221545',
    projectId: 'doctor-appointment-app-bb40a',
    storageBucket: 'doctor-appointment-app-bb40a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrN2Z95W1SQJKfJcVkCjLflj26g7S_Ug',
    appId: '1:866872221545:ios:b1ef65ba524bbd7a9ae7f8',
    messagingSenderId: '866872221545',
    projectId: 'doctor-appointment-app-bb40a',
    storageBucket: 'doctor-appointment-app-bb40a.appspot.com',
    iosClientId: '866872221545-8gdgstv462a9s89s4n245v8e345nacm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrN2Z95W1SQJKfJcVkCjLflj26g7S_Ug',
    appId: '1:866872221545:ios:b1ef65ba524bbd7a9ae7f8',
    messagingSenderId: '866872221545',
    projectId: 'doctor-appointment-app-bb40a',
    storageBucket: 'doctor-appointment-app-bb40a.appspot.com',
    iosClientId: '866872221545-8gdgstv462a9s89s4n245v8e345nacm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctor',
  );
}
